export { CourseFormPage } from './form-course';
export { ModuleForm, ModuleFormPage } from './form-module';
export { ProgramForm } from './form-program';
export { CourseView } from './course-view';
export { HomePage } from './home';
export { LoginPage } from './login';
export { ModuleView } from './module-view';
export { NotFoundPage } from './not-found';
export { ProgramView } from './program-view';
export { SettingsPage } from './settings';
export { ProfileEdit } from './settings';
export { DashboardView } from './dashboard-view';
export { DashWrapper } from './dash-wrapper';
