export { CourseFormPage } from './form-course';
export { ModuleForm, ModuleFormPage } from './form-module';
export { ProgramForm } from './form-program';
export { CourseView } from './view-course';
export { HomePage } from './home';
export { LoginPage } from './login';
export { ModuleView } from './view-module';
export { NotFoundPage } from './not-found';
export { ProgramView } from './view-program';
export { SettingsPage } from './settings';
export { ProfileEdit } from './settings';
export { DashboardView } from './view-dashboard';
export { DashWrapper } from './view-dash-wrapper';
